name: Taylor Peterson
description: Taylor Peterson's personal site

exclude:
  - 'README.md'
  - 'LICENSE'

permalink: /:categories/:title

collections:
  testcollection:
    output: true

source:       _source

data_dir:     _assets/data
includes_dir: _assets/includes
layouts_dir:  _assets/layouts
plugins_dir:  _assets/plugins
