collections:
  about_me:
    output: true
  knowledge_base:
    output: true
  landing_pages:
    output: true
  musings:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "" # All files in the project
    values:
      layout: "default"

description: "Taylor Peterson's personal site"

exclude:
  - 'CNAME'
  - 'docker-compose.yml'
  - 'LICENSE'
  - 'README.md'

includes_dir: _assets/_includes
layouts_dir:  _assets/_layouts

name: "Taylor Peterson"

permalink: /:categories/:title
