name: Taylor Peterson
description: Taylor Peterson's personal site

exclude:
  - 'README.md'
  - 'LICENSE'

permalink: /:categories/:title

collections:
  about_me:
    output: true
  knowledge_base:
    output: true
  landing_pages:
    output: true
  musings:
    output: true
  projects:
    output: true

layouts_dir:  _assets/_layouts
includes_dir: _assets/_includes
